language: java
        jdk:
                -oraclejdk8
                -oraclejdk9
                -openjdk7
        script:
                -jdk_switcher use roaclejdk8
                -jdk_switcher use openjdk7
